Feature/11147 implement dynamic datatype casting
eclipse-velocitas/vehicle-app-python-sdk pull request #26
Opened 2022-09-29 09:55 UTC by dennismeister93

## Describe your changes

Implement dynamic datatype casting for datapoints of the vehicle databroker response

## Issue ticket number and link

#AB[11147](https://softwaredefinedvehicle.visualstudio.com/SoftwareDefinedVehicle/_workitems/edit/11147)

## Checklist - Manual tasks

* [x] Examples are executing successfully
* [x] Created/updated unit tests. Code Coverage percentage on new code shall be >= 80%.
* [x] Created/updated integration tests.
* [x] Devcontainer can be opened successfully
* [x] Devcontainer can be opened successfully behind a corporate proxy
* [x] Devcontainer can be re-built successfully
* [x] Extended the documentation (e.g. README.md, CONTRIBUTING.md, Velocitas)

2022-10-07 06:27 UTC, emsameen requested changes
Rebase on main and Adjust the Dogmode app as well.

2022-10-07 06:27 UTC, emsameen commented on sdv/vdb/reply.py
> +    def get(self, datapoint_object):
rename the public API name to datapoint

2022-10-07 06:27 UTC, emsameen commented on sdv/vdb/reply.py
> +        datapoint: BrokerDatapoint = self._reply.fields[datapoint_object.get_path()]
rename to vdm_datapoint

2022-10-07 10:56 UTC, mml5bg approved these changes

2022-10-12 10:33 UTC, emsameen approved these changes

2022-10-12 10:35 UTC, emsameen approved these changes
The remaining open points are updated and approved by other commiter.

2022-10-12 10:37 UTC, merged