Adapt tests for seat adjuster to work after importing to template
eclipse-velocitas/vehicle-app-python-sdk pull request #88
Opened 2023-07-03 14:10 UTC by dennismeister93

## Describe your changes

Adapt tests for seat adjuster to work after importing to template

2023-07-03 15:31 UTC, BjoernAtBosch requested changes

2023-07-03 15:31 UTC, BjoernAtBosch commented on examples/seat-adjuster/tests/unit/test_run.py
>          assert response == get_error_response()
My impression is that we only test the mock with those tests ...
Real unit test should test calling e.g. `on_set_position_request_received` pasing a request and then mocks the speed get and checks if position set is triggered (if speed is 0) or an error is returned (if speed > 0 or position is out of range)

2023-07-03 15:31 UTC, BjoernAtBosch commented on examples/seat-adjuster/tests/integration/integration_test.py
> +
Remove

2023-07-06 09:15 UTC, BjoernAtBosch requested changes

2023-07-06 14:35 UTC, dennismeister93 commented on examples/seat-adjuster/src/vapp.py
> +logging.getLogger().setLevel("DEBUG")
unfortunately yes :(

2023-07-07 07:02 UTC, BjoernAtBosch approved these changes
LGTM

2023-07-07 08:14 UTC, merged